language: node_js
node_js:
  - "8.9.4"
install:
  - npm install
script:
  - npm run build
before_deploy:
  - source scripts/4660933598635778-openrc.sh
  - pip install python-swiftclient python-keystoneclient --user
deploy:
  # deploy next to the staging environment
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  # deploy next.seven23.io on github page
  - provider: pages
    skip_cleanup: true
    local_dir: build
    fqdn: https://next.seven23.io
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: develop
